version: "3"
services:
  nginx:
    image: nginx-simple:latest
    container_name: nginx-simpledc4
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./wwwroot/:/var/www/
    build:
      context: .
  php:
    build: ./php
    volumes: 
      - ./wwwroot/:/var/www/
  drush:
    image: drush/drush
    volumes:
      - ./wwwroot/:/var/www/
  mysqldb:
    image: mysql:5.7
    container_name: mysqldc4
    hostname: mysqldb
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/zz-php.ini
    ports:
      - 8081:8080
