version: "3"
services:
  nginx:
    container_name: nginx-simpledc4
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./wwwroot/:/var/www/
    build: ./contenta
  php:
    build: ./php
    volumes:
      - ./wwwroot/:/var/www/
  mysqldb:
    image: mysql:5.7
    container_name: mysqldc4
    hostname: mysqldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/zz-php.ini
    ports:
      - 8081:8080
  appserver:
    container_name: appserverdc4
    restart: always
    ports:
      - "8091:8091"
    volumes:
      - ./ngroot/:/var/www/
    build: ./appserver
